version: '2'
services:
  sysctl:
    image: busybox
    entrypoint:
      - sysctl
    command:
      - -w
      - vm.max_map_count=262144
    privileged: true
  elasticsearch:
    depends_on:
      - sysctl
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.1
    environment:
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK
    ports:
      - "9200:9200"
    volumes:
      - /usr/share/elasticsearch/data
  docker-fluentd-elasticsearch:
    build: ./docker-fluentd-elasticsearch
    image: mstrzele/docker-fluentd-elasticsearch
    ports:
      - "24224:24224"
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers
    links:
      - elasticsearch
  kibana:
    image: docker.elastic.co/kibana/kibana:5.3.1
    ports:
      - "5601:5601"
    links:
      - elasticsearch
  index-pattern:
    links:
      - kibana
    image: appropriate/curl
    command:
      - -d
      - '{"title" : "logstash-*",  "timeFieldName": "@timestamp"}'
      - -H
      - 'kbn-version: 5.3.1'
      - -X
      - PUT
      - --retry
      - "10"
      - --retry-connrefused
      - http://kibana:5601/es_admin/.kibana/index-pattern/logstash-*
