version: '2'
services:
  elasticsearch:
    image: elasticsearch:5.0
    command: elasticsearch -E network.host=0.0.0.0
    ports:
      - "9200:9200"
  custom-fluentd:
    build: ./custom-fluentd
    ports:
      - "24224:24224"
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers
    links:
      - elasticsearch
  kibana:
    image: kibana:5.0
    ports:
      - "5601:5601"
    links:
      - elasticsearch
